### ISSUE TITLE
Abbreviate street names and directions

### ISSUE THREAD

**Issue by jfrankl** [azavea/nih-wayfinding#106]
It would be great to abbreviate street names and directions on the navigation view. For example, 402 North 3rd Street would become 402 N 3rd St. This is going to allow us to use larger typography, which will be easier to read.

Here's a list of minimum street types I'd like abbreviated:
- Cir = Circle
- Hwy = Highway
- Pkwy = Parkway
- St = Street
- Rd = Road
- Ct = Court
- Ln = Lane
- Terr = Terrace
- Ave = Avenue
- Rdg = Ridge

Here's a more exhaustive list—I don't think it's necessary for this iteration, but might be just as easy: http://pe.usps.gov/text/pub28/28apc_002.htm

For directions:
- N = North
- S = South
- W = West
- E = East

**Comment by flibbertigibbet** [comment]
This may not be entirely straightforward, because words that in some contexts should be abbreviated, in others should not.  For example, "North Road" should not become "N Rd".  Or as with the Chicago neighborhood we're using, there's a "S South" something-or-other street.  In that context, we probably shouldn't abbreviate 'South' twice.  Also, it's possible some things might become ambiguous ('St' could be 'Street' or 'Saint').

**Comment by jfrankl** [comment]
From a design perspective, having long addresses limits us in terms of how we can display this data. If you look at Google Maps and Apple Maps apps, they abbreviate in the way that I'm describing, and it allows them to display addresses using larger type. I think that's going to be helpful for our users.

Here's a python-based solution that might work. Seems like it might not be too difficult to port it to javascript if needed:

https://github.com/nvkelso/map-label-style-manual/tree/master/tools/street_names

**Comment by flibbertigibbet** [comment]
I don't mean to suggest it's a bad idea.  It's not a simple search-and-replace, though.  There's alot of gotchas and exceptions with street addressing.

**Comment by CloudNiner** [comment]
I think that relatively simple solution @jfrankl presents might be manageable without being a ton of effort. Might be worth testing if time is available. I think anything more complicated than the linked solution would get quite difficult very quickly.

**Comment by flibbertigibbet** [comment]
Agreed.  I think the linked solution might be an oversimplification, as there can be multiple prefixes and/or suffixes, so it would be hard to figure out what the actual street name part is.  A simple solution might be good enough for demo purposes, though.  If we want to do something hairier, it might make sense to do that in OpenTripPlanner instead of client-side.
